### ISSUE TITLE
x's and o's

### ISSUE THREAD

**Issue by gfredericks** [mwalczyk/grid-diagrams#1]
What's the motivation for distinguishing x's from o's in the grid diagram definition? If my analysis is correct, you'd get the same result by saying "each row and column must have exactly two x's".

**Comment by garydunkerley** [comment]
Hello, 

You’re right that one could specify a link diagram using just one type of marking (e.g. X), but there are good reasons to insist on two different types of markings.

The first reason is simple: you need two different grid markings to encode an orientation on the components of your link. Orientations are useful.

![IMG_1521](https://github.com/mwalczyk/grid-diagrams/assets/58280110/597c95f5-1b5d-46e4-9049-3eb6f2a63e68)

The second reason is more complicated but it’s the entire reason people care about grid diagrams in the first place. 

Grid diagrams are leveraged to compute a link invariant called the grid homology; it’s equivalent to a powerful link invariant called the link Floer homology. The advantage grid homology has over link Floer is that it can theoretically be computed directly from a grid diagram algorithmically; computing the link Floer homology often can’t be computed directly from a link diagram. This reason is a little silly because the computational complexity of grid homology grows very quickly as the grid size expands; the real reason people like grid homology is because it has simple formal properties. 

For example, there’s a historically difficult theorem called the Milnor Conjecture which was initially proven by [Kronheimer and Mrowka in 1992](https://people.math.harvard.edu/~kronheim/thomconj.pdf) using difficult, gauge theoretic techniques. On the other hand, there’s a neat knot invariant called tau which is derived from knot Floer homology: it’s neat because proving it’s well-defined and has the properties that it has immediately yields the Milnor conjecture. Since grid homology is equivalent to knot Floer, you can also use grid homology to compute tau. Leveraging this, Sucharit Sarkar gave [a greatly simplified proof of the Milnor conjecture](https://arxiv.org/abs/1011.5265).

The X’s and O’s are critical for defining grid homology. I’m not sure what your background is, but I’ll try to give a sketch while leaning on intuition you might have from a course on linear algebra. Details are all found in an excellent book (from which I cribbed all figures): [Grid Homology for Knots and Links](https://web.math.princeton.edu/~petero/GridHomologyBook.pdf) by Peter Oszváth, András Stipsicz, and Zoltán Szabó.

The grid homology GH(L) of a link L is an example of an algebraic gadget called a module (slight generalizations of vector spaces, it’s fine to think of them as vector spaces if this helps). This module has some extra structure called a bigrading, meaning it can be thought of as a bunch of smaller modules all lumped together which are indexed by pairs of integers (q,a) (e.g. each vector space has an “address”). People call the value q the Maslov grading and a the Alexander grading.

When one computes grid homology for a link L, you begin with a bigraded module GC(L) which is equipped with a linear map 

d : GC(L) —> GC(L)

that satisfies the condition that d(d(x))=0 for any element (e.g. vector) x in GC(L). Any object with structure as above is called a bigraded chain complex and the elements of GC(L) are called chains.

As in linear algebra, the collection of chains x such that d(x)=0 is called the kernel of d. The homology is the result of taking a quotient (not dissimilar to a quotient of vector spaces) of the kernel of d by the image of d. Each chain element in the complex is sent to an equivalence class under this quotient operation and we call this equivalence class an element of the grid homology GH(L). The bigrading on GC(L) induces a bigrading on its homology.

Defining the Maslov and Alexander gradings on GC(L) requires that we distinguish two different types of grid markings (X and O) for our diagram of L. Chains in GC(L) are generated by arrangements of n points at the intersections of the grid lines such that the collection contains a single point in each horizontal/vertical line (Important: the lines at the top/bottom and far left/far right are treated as being identical, as if on a torus). These point arrangements are called grid states.

One defines the Maslov grading on GC(L) by declaring a particular grid state associated to the O-markings of the grid diagram as having Maslov grading 0 and uses a formula to determine the Maslov gradings of all other grid states relative to our “north star” (the state associated to the O-markings). The definition of the Alexander grading is a bit more complicated and it requires both X and O markings. 

The map d sends each grid state x to a weighted sum across all other grid states y. Roughly, for fixed y, its associated weight as a summand in d(x) is determined by how many “rectangles” in the grid diagram “connect” the state x to the state y. 
![IMG_1522](https://github.com/mwalczyk/grid-diagrams/assets/58280110/a295b69a-0eda-434c-9125-de89de847a89)

There are several versions of grid homology that differ in which rectangles “count” according to how many X’s and O’s they contain. For the “fully blocked” version of grid homology, you only count rectangles containing no O’s. For the “minus version”, you allow O’s in your rectangles and keep track of how many there are. In both versions, rectangles containing X’s are not counted at all, another reason why we need both!

Hopefully this was helpful / interesting.

Cheers,

Gary

**Comment by gfredericks** [comment]
That's very helpful, thanks a bunch!
